"""empty message

Revision ID: 4f8ae4c6bae
Revises: None
Create Date: 2016-07-21 15:59:46.547311

"""

# revision identifiers, used by Alembic.
revision = '4f8ae4c6bae'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
